import type { Metadata } from "next";
import { Hanken_Grotesk } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Hanken_Grotesk({ weight: '400', subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-row items-center text-7xl w-auto"><Image src={'/logo.svg'} className="mx-5" alt="logo" width={100} height={100} />EIBERTEK</div>        
        {children}
      </body>
    </html>
  );
}
